# Generated by Django 4.1.2 on 2022-10-19 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('stars', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('categories', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('yelping_since', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stars', models.FloatField()),
                ('useful', models.IntegerField()),
                ('funny', models.IntegerField()),
                ('cool', models.IntegerField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.user')),
            ],
        ),
    ]
