# Generated by Django 4.1.2 on 2022-10-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_rename_business_id_review_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='business',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
