# Generated by Django 4.1.2 on 2022-10-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_alter_review_business_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='business',
            new_name='business_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
    ]
